<?php

use App\Http\Controllers\Admin\AlumniAccountController;
use App\Http\Controllers\Admin\DestroyArchivedEventCommentController;
use App\Http\Controllers\Admin\DestroyJobController;
use App\Http\Controllers\Admin\SendApplicantResumeController;
use App\Http\Controllers\Admin\StoreAccountController;
use App\Http\Controllers\Admin\UpdateAlumniApprovalController;
use App\Http\Controllers\Alumni\DestroyEmploymentController;
use App\Http\Controllers\Alumni\StoreEducationController;
use App\Http\Controllers\Alumni\StoreEmploymentController;
use App\Http\Controllers\Application\AlumniApplicationActionController;
use App\Http\Controllers\Application\StoreApplicationController;
use App\Http\Controllers\Application\UpdateApplicationStatusController;
use App\Http\Controllers\Employer\DestroyJobController as EmployerDestroyJobController;
use App\Http\Controllers\Employer\SendJobOfferController;
use App\Http\Controllers\Event\ArchiveEventController;
use App\Http\Controllers\Event\DestroyEventController;
use App\Http\Controllers\Event\EventIndexController;
use App\Http\Controllers\Event\RestoreEventController;
use App\Http\Controllers\Event\StoreEventController;
use App\Http\Controllers\Event\UpdateEventController;
use App\Http\Controllers\Interview\ScheduleInterviewController;
use App\Http\Controllers\Job\SendJobNotificationController;
use App\Http\Controllers\Job\StoreJobController;
use App\Http\Controllers\Job\UpdateJobController;
use App\Http\Controllers\Pages\AdminAdminArchiveController;
use App\Http\Controllers\Pages\AdminAlumniCreateController;
use App\Http\Controllers\Pages\AdminAlumniEditController;
use App\Http\Controllers\Pages\AdminAlumniListController;
use App\Http\Controllers\Pages\AdminAlumniReportController;
use App\Http\Controllers\Pages\AdminApplicationsController;
use App\Http\Controllers\Pages\AdminCreateAlumniOfficerController;
use App\Http\Controllers\Pages\AdminCreateEmployerController;
use App\Http\Controllers\Pages\AdminDashboardController;
use App\Http\Controllers\Pages\AdminEventsCreateController;
use App\Http\Controllers\Pages\AdminEventsEditController;
use App\Http\Controllers\Pages\AdminEventsListController;
use App\Http\Controllers\Pages\AdminForwardToCompanyController;
use App\Http\Controllers\Pages\AdminGraduatesListController;
use App\Http\Controllers\Pages\AdminGraduatesReportController;
use App\Http\Controllers\Pages\AdminGraduatesStatsController;
use App\Http\Controllers\Pages\AdminInterviewController;
use App\Http\Controllers\Pages\AdminJobsCreateController;
use App\Http\Controllers\Pages\AdminJobsEditController;
use App\Http\Controllers\Pages\AdminJobsListController;
use App\Http\Controllers\Pages\AdminJobsNotifyController;
use App\Http\Controllers\Pages\AdminPendingAlumniController;
use App\Http\Controllers\Pages\AdminReportsController;
use App\Http\Controllers\Pages\AlumniAddDegreeController;
use App\Http\Controllers\Pages\AlumniApplyController;
use App\Http\Controllers\Pages\AlumniChangePasswordController;
use App\Http\Controllers\Pages\AlumniEditProfileController;
use App\Http\Controllers\Pages\AlumniEmploymentHistoryController;
use App\Http\Controllers\Pages\AlumniFeedController;
use App\Http\Controllers\Pages\AlumniJobDetailsController;
use App\Http\Controllers\Pages\AlumniJobsController;
use App\Http\Controllers\Pages\AlumniMyApplicationsController;
use App\Http\Controllers\Pages\AlumniOfficerAlumniListController;
use App\Http\Controllers\Pages\AlumniOfficerArchiveController;
use App\Http\Controllers\Pages\AlumniOfficerDashboardController;
use App\Http\Controllers\Pages\AlumniOfficerEventsCreateController;
use App\Http\Controllers\Pages\AlumniOfficerEventsEditController;
use App\Http\Controllers\Pages\AlumniOfficerEventsListController;
use App\Http\Controllers\Pages\ArchiveController;
use App\Http\Controllers\Pages\EmployerAlumniListController;
use App\Http\Controllers\Pages\EmployerApplicationsController;
use App\Http\Controllers\Pages\EmployerDashboardController;
use App\Http\Controllers\Pages\EmployerInterviewController;
use App\Http\Controllers\Pages\EmployerPostedJobController;
use App\Http\Controllers\Pages\EmployerPostJobController;
use App\Http\Controllers\Pages\ProfileController;
use App\Http\Controllers\Profile\DestroyCertificateController;
use App\Http\Controllers\Profile\StoreCertificateController;
use App\Http\Controllers\Profile\UpdateAccountProfileController;
use App\Http\Controllers\Profile\UpdateNotificationPreferenceController;
use App\Http\Controllers\Profile\UpdateOwnProfileController;
use App\Http\Controllers\Profile\UpdatePasswordController;
use App\Http\Controllers\SocialFeedActionController;
use Illuminate\Support\Facades\Route;

Route::get('/admin/admin_archive', AdminAdminArchiveController::class)->middleware('account:admin')->name('admin.admin_archive');
Route::delete('/admin/archive/events/{event}/comments/{comment}', DestroyArchivedEventCommentController::class)->middleware('account:admin')->name('admin.archive.comments.destroy');
Route::get('/admin/alumni_create', AdminAlumniCreateController::class)->middleware('account:admin')->name('admin.alumni_create');
Route::post('/admin/alumni', [StoreAccountController::class, 'alumni'])->middleware('account:admin')->name('admin.alumni.store');
Route::get('/admin/alumni_edit', AdminAlumniEditController::class)->middleware('account:admin')->name('admin.alumni_edit');
Route::put('/admin/alumni/{alumni}', [AlumniAccountController::class, 'update'])->middleware('account:admin')->name('admin.alumni.update');
Route::delete('/admin/alumni/{alumni}', [AlumniAccountController::class, 'destroy'])->middleware('account:admin')->name('admin.alumni.destroy');
Route::get('/admin/alumni_list', AdminAlumniListController::class)->middleware('account:admin')->name('admin.alumni_list');
Route::get('/admin/alumni_report', AdminAlumniReportController::class)->middleware('account:admin')->name('admin.alumni_report');
Route::get('/admin/applications', AdminApplicationsController::class)->middleware('account:admin')->name('admin.applications');
Route::get('/admin/create_alumni_officer', AdminCreateAlumniOfficerController::class)->middleware('account:admin')->name('admin.create_alumni_officer');
Route::post('/admin/alumni-officers', [StoreAccountController::class, 'officer'])->middleware('account:admin')->name('admin.alumni-officers.store');
Route::get('/admin/create_employer', AdminCreateEmployerController::class)->middleware('account:admin')->name('admin.create_employer');
Route::post('/admin/employers', [StoreAccountController::class, 'employer'])->middleware('account:admin')->name('admin.employers.store');
Route::get('/admin/dashboard', AdminDashboardController::class)->middleware('account:admin')->name('admin.dashboard');
Route::get('/admin/events_create', AdminEventsCreateController::class)->middleware('account:admin')->name('admin.events_create');
Route::get('/admin/events_delete', fn () => to_route('admin.events_list'))->middleware('account:admin')->name('admin.events_delete');
Route::get('/admin/events_edit', AdminEventsEditController::class)->middleware('account:admin')->name('admin.events_edit');
Route::get('/admin/events_list', AdminEventsListController::class)->middleware('account:admin')->name('admin.events_list');
Route::get('/admin/forward_to_company', AdminForwardToCompanyController::class)->middleware('account:admin')->name('admin.forward_to_company');
Route::post('/admin/applications/{application}/forward-resume', SendApplicantResumeController::class)->middleware('account:admin')->name('admin.applications.resume.send');
Route::get('/admin/graduates_list', AdminGraduatesListController::class)->middleware('account:admin')->name('admin.graduates_list');
Route::get('/admin/graduates_report', AdminGraduatesReportController::class)->middleware('account:admin')->name('admin.graduates_report');
Route::get('/admin/graduates_stats', AdminGraduatesStatsController::class)->middleware('account:admin')->name('admin.graduates_stats');
Route::get('/admin/interview', AdminInterviewController::class)->middleware('account:admin')->name('admin.interview');
Route::get('/admin/jobs_create', AdminJobsCreateController::class)->middleware('account:admin')->name('admin.jobs_create');
Route::get('/admin/jobs_edit', AdminJobsEditController::class)->middleware('account:admin')->name('admin.jobs_edit');
Route::get('/admin/jobs_list', AdminJobsListController::class)->middleware('account:admin')->name('admin.jobs_list');
Route::delete('/admin/jobs/{job}', DestroyJobController::class)->middleware('account:admin')->name('admin.jobs.destroy');
Route::post('/jobs', StoreJobController::class)->middleware('account:admin,employer')->name('jobs.store');
Route::put('/jobs/{job}', UpdateJobController::class)->middleware('account:admin,employer')->name('jobs.update');
Route::get('/admin/jobs_notify', AdminJobsNotifyController::class)->middleware('account:admin')->name('admin.jobs_notify');
Route::post('/admin/jobs/{job}/notifications', SendJobNotificationController::class)->middleware('account:admin')->name('admin.jobs.notifications.store');
Route::get('/admin/offers_history', fn () => to_route('admin.reports', status: 301))->middleware('account:admin')->name('admin.offers_history');
Route::get('/admin/pending_alumni', AdminPendingAlumniController::class)->middleware('account:admin')->name('admin.pending_alumni');
Route::patch('/admin/alumni/{alumni}/approval', [UpdateAlumniApprovalController::class, 'approve'])->middleware('account:admin')->name('admin.alumni.approve');
Route::patch('/admin/alumni/{alumni}/rejection', [UpdateAlumniApprovalController::class, 'reject'])->middleware('account:admin')->name('admin.alumni.reject');
Route::get('/admin/reports', AdminReportsController::class)->middleware('account:admin')->name('admin.reports');
Route::get('/alumni/add_degree', AlumniAddDegreeController::class)->middleware('account:alumni')->name('alumni.add_degree');
Route::post('/profile/education', StoreEducationController::class)->middleware('account:alumni')->name('alumni.education.store');
Route::get('/alumni/apply', AlumniApplyController::class)->middleware('account:alumni')->name('alumni.apply');
Route::post('/alumni/jobs/{job}/applications', StoreApplicationController::class)->middleware('account:alumni')->name('applications.store');
Route::get('/alumni/change_password', AlumniChangePasswordController::class)->middleware('account:alumni')->name('alumni.change_password');
Route::get('/alumni/dashboard', fn () => to_route('alumni.feed'))->middleware('account:alumni')->name('alumni.dashboard');
Route::get('/alumni/edit_profile', AlumniEditProfileController::class)->middleware('account:alumni')->name('alumni.edit_profile');
Route::put('/profile/details', UpdateOwnProfileController::class)->middleware('account:alumni')->name('alumni.profile.update');
Route::get('/alumni/employment_history', AlumniEmploymentHistoryController::class)->middleware('account:alumni')->name('alumni.employment_history');
Route::post('/profile/employment', StoreEmploymentController::class)->middleware('account:alumni')->name('alumni.employment.store');
Route::delete('/alumni/employment/{employment}', DestroyEmploymentController::class)->middleware('account:alumni')->name('alumni.employment.destroy');
Route::get('/alumni/feed', AlumniFeedController::class)->middleware('account:alumni')->name('alumni.feed');
Route::get('/alumni/job_details', AlumniJobDetailsController::class)->middleware('account:alumni')->name('alumni.job_details');
Route::get('/alumni/job_offers', fn () => to_route('alumni.jobs', status: 301))->middleware('account:alumni')->name('alumni.job_offers');
Route::get('/alumni/jobs', AlumniJobsController::class)->middleware('account:alumni')->name('alumni.jobs');
Route::get('/alumni/my_applications', AlumniMyApplicationsController::class)->middleware('account:alumni')->name('alumni.my_applications');
Route::patch('/alumni/applications/{application}/cancel', [AlumniApplicationActionController::class, 'cancel'])->middleware('account:alumni')->name('applications.cancel');
Route::delete('/alumni/applications/{application}', [AlumniApplicationActionController::class, 'destroy'])->middleware('account:alumni')->name('applications.destroy');
Route::get('/alumni_officer/alumni_list', AlumniOfficerAlumniListController::class)->middleware('account:alumni_officer')->name('alumni_officer.alumni_list');
Route::get('/alumni_officer/archive', AlumniOfficerArchiveController::class)->middleware('account:alumni_officer')->name('alumni_officer.archive');
Route::get('/alumni_officer/dashboard', AlumniOfficerDashboardController::class)->middleware('account:alumni_officer')->name('alumni_officer.dashboard');
Route::get('/alumni_officer/events_create', AlumniOfficerEventsCreateController::class)->middleware('account:alumni_officer')->name('alumni_officer.events_create');
Route::get('/alumni_officer/events_edit', AlumniOfficerEventsEditController::class)->middleware('account:alumni_officer')->name('alumni_officer.events_edit');
Route::get('/alumni_officer/events_list', AlumniOfficerEventsListController::class)->middleware('account:alumni_officer')->name('alumni_officer.events_list');
Route::get('/employer/alumni_list', EmployerAlumniListController::class)->middleware('account:employer')->name('employer.alumni_list');
Route::post('/employer/job-offers', SendJobOfferController::class)->middleware(['account:employer', 'throttle:10,1'])->name('employer.offers.store');
Route::get('/employer/applications', EmployerApplicationsController::class)->middleware('account:employer')->name('employer.applications');
Route::get('/employer/dashboard', EmployerDashboardController::class)->middleware('account:employer')->name('employer.dashboard');
Route::get('/employer/community', AlumniFeedController::class)->middleware('account:employer')->name('employer.community');
Route::get('/employer/interview', EmployerInterviewController::class)->middleware('account:employer')->name('employer.interview');
Route::get('/employer/job_offers', fn () => to_route('employer.posted_job', status: 301))->middleware('account:employer')->name('employer.job_offers');
Route::get('/employer/post_job', EmployerPostJobController::class)->middleware('account:employer')->name('employer.post_job');
Route::get('/employer/posted_job', EmployerPostedJobController::class)->middleware('account:employer')->name('employer.posted_job');
Route::delete('/employer/jobs/{job}', EmployerDestroyJobController::class)->middleware('account:employer')->name('employer.jobs.destroy');
Route::get('/profile', ProfileController::class)->middleware('account')->name('profile');
Route::patch('/profile/notifications', UpdateNotificationPreferenceController::class)->middleware('account:alumni')->name('profile.notifications.update');
Route::post('/profile/certificates', StoreCertificateController::class)->middleware('account:alumni')->name('profile.certificates.store');
Route::put('/profile', UpdateAccountProfileController::class)->middleware('account')->name('profile.update');
Route::put('/profile/password', UpdatePasswordController::class)->middleware('account')->name('profile.password.update');
Route::patch('/applications/{application}/status', UpdateApplicationStatusController::class)->middleware('account:admin,employer')->name('applications.status.update');
Route::post('/interviews', ScheduleInterviewController::class)->middleware('account:admin,employer')->name('interviews.store');
Route::delete('/profile/certificates/{certificate}', DestroyCertificateController::class)->middleware('account')->name('profile.certificates.destroy');
Route::get('/events', EventIndexController::class)->middleware('account')->name('events.index');
Route::patch('/events/{event}/restore', RestoreEventController::class)->middleware('account')->name('events.restore');
Route::patch('/events/{event}/archive', ArchiveEventController::class)->middleware('account')->name('events.archive');
Route::delete('/events/{event}', DestroyEventController::class)->middleware('account:admin,alumni_officer')->name('events.destroy');
Route::post('/events', StoreEventController::class)->middleware('account')->name('events.store');
Route::post('/feed/{type}/{post}/reaction', [SocialFeedActionController::class, 'reaction'])->where('type', 'event')->middleware('account:admin,alumni,alumni_officer,employer')->name('feed.reactions.store');
Route::post('/feed/{type}/{post}/comments', [SocialFeedActionController::class, 'comment'])->where('type', 'event')->middleware('account:admin,alumni,alumni_officer,employer')->name('feed.comments.store');
Route::delete('/feed/comments/{comment}', [SocialFeedActionController::class, 'destroyComment'])->middleware('account:admin,alumni,alumni_officer,employer')->name('feed.comments.destroy');
Route::put('/events/{event}', UpdateEventController::class)->middleware('account')->name('events.update');
Route::get('/archive', ArchiveController::class)->middleware('account:alumni_officer')->name('archive');
